[build]
  publish = "."
  command = "echo 'No build step required for static site'"

[functions]
  directory = "functions"

[[redirects]]
  from = "/rss-proxy"
  to = "/.netlify/functions/proxy"
  status = 200
